# Generated by Django 3.2.13 on 2022-05-06 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_auto_20220504_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_entry', models.TextField()),
                ('Pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.pizza')),
            ],
        ),
    ]
