# Generated by Django 3.2.13 on 2022-05-06 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
