# Generated by Django 3.2.13 on 2022-05-06 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_entry', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('Pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.pizza')),
            ],
        ),
    ]
